package Model;
// Generated 10/09/2021 12:27:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idempleado;
     private Sucursal sucursal;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String direccion;
     private Double salario;
     private Character sexo;
     private Date fechanacimiento;
     private Date horaentrada;
     private String curp;
     private Long telefono;
     private Set<Venta> ventas = new HashSet<Venta>(0);

    public Empleado() {
        
        sucursal = new Sucursal();
                
    }

    public Empleado(Sucursal sucursal, String nombre, String apellidoPaterno, String apellidoMaterno, String direccion, Double salario, Character sexo, Date fechanacimiento, Date horaentrada, String curp, Long telefono, Set<Venta> ventas) {
       this.sucursal = sucursal;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.direccion = direccion;
       this.salario = salario;
       this.sexo = sexo;
       this.fechanacimiento = fechanacimiento;
       this.horaentrada = horaentrada;
       this.curp = curp;
       this.telefono = telefono;
       this.ventas = ventas;
    }
   
    public Integer getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(Integer idempleado) {
        this.idempleado = idempleado;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Double getSalario() {
        return this.salario;
    }
    
    public void setSalario(Double salario) {
        this.salario = salario;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }
    public Date getHoraentrada() {
        return this.horaentrada;
    }
    
    public void setHoraentrada(Date horaentrada) {
        this.horaentrada = horaentrada;
    }
    public String getCurp() {
        return this.curp;
    }
    
    public void setCurp(String curp) {
        this.curp = curp;
    }
    public Long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Long telefono) {
        this.telefono = telefono;
    }
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }




}


