package Model;
// Generated 10/09/2021 12:27:32 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provedor generated by hbm2java
 */
public class Provedor  implements java.io.Serializable {


     private Integer idprovedor;
     private String nombre;
     private String productos;
     private String direccion;
     private String correo;
     private String rfc;
     private Long telefono;
     private Set<Producto> productos_1 = new HashSet<Producto>(0);

    public Provedor() {
        
    }

    public Provedor(String nombre, String productos, String direccion, String correo, String rfc, Long telefono, Set<Producto> productos_1) {
       this.nombre = nombre;
       this.productos = productos;
       this.direccion = direccion;
       this.correo = correo;
       this.rfc = rfc;
       this.telefono = telefono;
       this.productos_1 = productos_1;
    }
   
    public Integer getIdprovedor() {
        return this.idprovedor;
    }
    
    public void setIdprovedor(Integer idprovedor) {
        this.idprovedor = idprovedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getProductos() {
        return this.productos;
    }
    
    public void setProductos(String productos) {
        this.productos = productos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public Long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Long telefono) {
        this.telefono = telefono;
    }
    public Set<Producto> getProductos_1() {
        return this.productos_1;
    }
    
    public void setProductos_1(Set<Producto> productos_1) {
        this.productos_1 = productos_1;
    }




}


