package Model;
// Generated 10/09/2021 12:27:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal  implements java.io.Serializable {


     private Integer idsucursal;
     private String nombre;
     private String direccion;
     private Integer numeroempleados;
     private String rfc;
     private Date horaapertura;
     private String correo;
     private Long telefono;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);
     private Set<Venta> ventas = new HashSet<Venta>(0);

    public Sucursal() {
    }

    public Sucursal(String nombre, String direccion, Integer numeroempleados, String rfc, Date horaapertura, String correo, Long telefono, Set<Empleado> empleados, Set<Venta> ventas) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.numeroempleados = numeroempleados;
       this.rfc = rfc;
       this.horaapertura = horaapertura;
       this.correo = correo;
       this.telefono = telefono;
       this.empleados = empleados;
       this.ventas = ventas;
    }
   
    public Integer getIdsucursal() {
        return this.idsucursal;
    }
    
    public void setIdsucursal(Integer idsucursal) {
        this.idsucursal = idsucursal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getNumeroempleados() {
        return this.numeroempleados;
    }
    
    public void setNumeroempleados(Integer numeroempleados) {
        this.numeroempleados = numeroempleados;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public Date getHoraapertura() {
        return this.horaapertura;
    }
    
    public void setHoraapertura(Date horaapertura) {
        this.horaapertura = horaapertura;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Long telefono) {
        this.telefono = telefono;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }




}


