package Model;
// Generated 10/09/2021 12:27:32 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer idventa;
     private Clientes clientes;
     private Empleado empleado;
     private Producto producto;
     private Sucursal sucursal;
     private Date fechaventa;
     private Date horaventa;
     private Integer montototal;

    public Venta() {
        
        clientes = new Clientes();
        empleado = new Empleado();
        producto = new Producto();
        sucursal = new Sucursal();
    }

    public Venta(Clientes clientes, Empleado empleado, Producto producto, Sucursal sucursal, Date fechaventa, Date horaventa, Integer montototal) {
       this.clientes = clientes;
       this.empleado = empleado;
       this.producto = producto;
       this.sucursal = sucursal;
       this.fechaventa = fechaventa;
       this.horaventa = horaventa;
       this.montototal = montototal;
    }
   
    public Integer getIdventa() {
        return this.idventa;
    }
    
    public void setIdventa(Integer idventa) {
        this.idventa = idventa;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public Date getFechaventa() {
        return this.fechaventa;
    }
    
    public void setFechaventa(Date fechaventa) {
        this.fechaventa = fechaventa;
    }
    public Date getHoraventa() {
        return this.horaventa;
    }
    
    public void setHoraventa(Date horaventa) {
        this.horaventa = horaventa;
    }
    public Integer getMontototal() {
        return this.montototal;
    }
    
    public void setMontototal(Integer montototal) {
        this.montototal = montototal;
    }
}


